<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <VersionPrefix>0.1.2</VersionPrefix>
    <AssemblyName>ChromaDB.VectorData</AssemblyName>
    <PackageId>ChromaDotNet.VectorData</PackageId>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;net462</TargetFrameworks>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>

    <Title>Chroma provider for Microsoft.Extensions.VectorData</Title>
    <Description>Chroma provider for Microsoft.Extensions.VectorData, built on ChromaDotNet.Client.</Description>
    <PackageTags>chroma chromadb vector database vectordata ai</PackageTags>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Linq.AsyncEnumerable" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="ChromaDotNet.Client" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net462' ">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <Reference Include="System.Net.Http" />
    <Using Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ChromaDB.VectorData.UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>