<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;$(NetFrameworkTfm)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <RootNamespace>ChromaDB.VectorData.ConformanceTests</RootNamespace>
    <!-- The TextSearchStore of Semantic Kernel is experimental. -->
    <NoWarn>$(NoWarn);SKEXP0001;SKEXP0130</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ChromaDotNet.Testcontainers" />
    <PackageReference Include="ChromaDotNet.Client.DependencyInjection" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\ChromaDB.VectorData\ChromaDB.VectorData.csproj" />
    <PackageReference Include="Microsoft.Extensions.VectorData.ConformanceTests" />
  </ItemGroup>

</Project>
